# Additional configuration options for `cargo clippy`.
# https://doc.rust-lang.org/clippy/configuration.html

# https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
doc-valid-idents = [".."]
